### PR TITLE
Fixed sub-topic for commons to … mapping.

### PR DESCRIPTION
**Pull request by wsobel**

### CODE REVIEW

**Review by mereolog — APPROVED** [review]

**Review by kbserm — APPROVED** [review]
I think for this kind of change @MilosDrobnjakovic is better reviewer than me.

**Review by MilosDrobnjakovic — CHANGES_REQUESTED** [review]
Please change the following:  
From:  > This ontology maps the OMG Common Ontologies concepts to those of IOF Core.
 TO: > This ontology maps the OMG Common Ontologies concepts related to the notion of Identifier to those of IOF Core. Specifically, the OMG ontologies Collections, Designators and Identifiers are mapped to the IOF Core. 
> The purpose of this ontology is to ensure interoperability with the listed OMG Ontologies and to enable users of IOF Core to utilize OMG constructs around identifiers that are currently lacking within the IOF Core.

**Comment by wsobel** [comment]
Milos, please review changes per your request.

**Review by MilosDrobnjakovic — APPROVED** [review]
The change looks good to me. @kbserm  please check if there is anything that needs to be modified.

**Comment by wsobel** [comment]
@ekwallace, Please review changes before I merge.

**Pull request merged**
