### PR TITLE
pull the latest changes from Product service system dev to the PSSInformation branch

### PR DESCRIPTION
**Pull request by atcorreia**
The update product-service-system-dev branch has already some of the needed changes fixed

### CODE REVIEW

**Review by M3t4Mash — APPROVED** [review]

**Comment by mereolog** [comment]
@atcorreia could you resolve the merge conflicts?

**Comment by mereolog** [comment]
This pull request will not get through the CI Jenkins pipeline because the branch name, [PSS/PSS-3-PPSInformation-using-hasRole-contradicts-domain-of-hasRole-in-Core](https://github.com/iofoundry/ontology/tree/PSS/PSS-3-PPSInformation-using-hasRole-contradicts-domain-of-hasRole-in-Core) , contains the '/' char, which treated as a special character in branch names. Note that this branch name does not follow the rules defined in https://oagi.atlassian.net/wiki/spaces/IOF/pages/4591976461/Proposed+GitHub+User+Branch+and+Merge+Rules.


Would it be possible to rename the branch so that it does not contain the '/' char - see for example: https://stackoverflow.com/questions/30590083/git-how-to-rename-a-branch-both-local-and-remote ?

**Comment by M3t4Mash** [comment]
@mereolog The rules regarding branch naming seem to imply that branch names can contain a prefix and a /. Maybe that's a recent change? 
The rules seem to prohibit using the pattern <key>/<key>-<issue #> though.  Not sure why. The pattern used in this branch name allows folder-support in git clients and also linking to the jira issue.  

For the rules, see:
https://oagi.atlassian.net/wiki/spaces/IOF/pages/4591976461/Proposed+GitHub+User+Branch+and+Merge+Rules#:~:text=You%20MUST%20use%20one%20of%20the%20following%20formats

And here's the link to the branch in the issue: 
https://oagi.atlassian.net/browse/PSS-3

If the naming is causing trouble though, then we can change it. We were just hoping to have them neatly grouped and also linked in the jira issue.

**Comment by mereolog** [comment]
> @mereolog The rules regarding branch naming seem to imply that branch names can contain a prefix and a /. Maybe that's a recent change? The rules seem to prohibit using the pattern <key>/<key>-<issue #> though. Not sure why. The pattern used in this branch name allows folder-support in git clients and also linking to the jira issue.
> 
> For the rules, see: https://oagi.atlassian.net/wiki/spaces/IOF/pages/4591976461/Proposed+GitHub+User+Branch+and+Merge+Rules#:~:text=You%20MUST%20use%20one%20of%20the%20following%20formats
> 
> And here's the link to the branch in the issue: https://oagi.atlassian.net/browse/PSS-3
> 
> If the naming is causing trouble though, then we can change it. We were just hoping to have them neatly grouped and also linked in the jira issue.

Yes, you are right as far as the OAGI rules are concerned - they allow for '/' in branch names.

However, as of now, the CI process does not handle such names - we can probably somehow hack this, but it will take some time.

**Comment by wsobel** [comment]
I did make it optional to use a / in the branch name to support tools. The optional separator character should be either `/` or `-`. 

If this is a problem, we can change the rules.

**Pull request closed without merging**
